import { subDays } from "date-fns"

export const persons = [
  { firstName: "Caroline", lastName: "Toberman", email: "caroline.toberman@example.com" },
  { firstName: "Madison", lastName: "Maxwell", email: "madison.maxwell@example.com" },
  { firstName: "Milani", lastName: "Lee", email: "milani.lee@example.com" },
  { firstName: "Laurel", lastName: "Barsocchini", email: "laurel.barsocchini@example.com" },
  { firstName: "Victoria", lastName: "Davis", email: "victoria.davis@example.com" },
  { firstName: "Bridget", lastName: "Conley", email: "bridget.conley@example.com" },
  { firstName: "Hannah", lastName: "Shaffer", email: "hannah.shaffer@example.com" },
  { firstName: "Jaydin", lastName: "Watts", email: "jaydin.watts@example.com" },
  { firstName: "Benjamin", lastName: "Wilson", email: "benjamin.wilson@example.com" },
  { firstName: "Mia", lastName: "Lopez", email: "mia.lopez@example.com" },
]

export const games = [
  {
    title: "Game 1",
    slug: "game-1",
    description: "Season Opener",
    date: subDays(new Date(), 7),
    teamScore: 25,
    opponentScore: 20,
  },
  {
    title: "Game 2",
    slug: "game-2",
    description: "Tough Opponent",
    date: subDays(new Date(), 5),
    teamScore: 25,
    opponentScore: 22,
  },
  {
    title: "Game 3",
    slug: "game-3",
    description: "Mid-season Battle",
    date: subDays(new Date(), 3),
    teamScore: 18,
    opponentScore: 25,
  },
  {
    title: "Game 4",
    slug: "game-4",
    description: "Final Showdown",
    date: subDays(new Date(), 1),
    teamScore: 25,
    opponentScore: 20,
  },
]

export const gameStatistics = [
  [
    {
      name: "Caroline Toberman",
      serveAces: 2,
      serveErrors: 1,
      serveAttempts: 10,
      servePercentage: 0.9,
      serveEfficiency: 0.1,
      serveRating: 2.1,
      receivePerfect: 2,
      receivePositive: 3,
      receiveNegative: 0,
      receiveAttempts: 5,
      receivePercentage: 2.4,
      setAssists: 1,
      setsTotal: 4,
      setErrors: 0,
      digs: 8,
      digErrors: 0,
      setsPlayed: 2,
    },
    {
      name: "Madison Maxwell",
      kills: 10,
      attackErrors: 2,
      attackAttempts: 18,
      attackEfficiency: 0.44,
      killsPerSet: 5,
      serveAces: 0,
      serveErrors: 1,
      serveAttempts: 9,
      servePercentage: 0.89,
      serveEfficiency: -0.11,
      serveRating: 1.5,
      receivePerfect: 2,
      receivePositive: 5,
      receiveNegative: 2,
      receiveAttempts: 9,
      receivePercentage: 1.67,
      setAssists: 5,
      setsTotal: 25,
      setErrors: 1,
      digs: 10,
      digErrors: 1,
      setsPlayed: 2,
    },
    {
      name: "Milani Lee",
      kills: 6,
      attackErrors: 3,
      attackAttempts: 17,
      attackEfficiency: 0.18,
      killsPerSet: 3,
      serveAces: 1,
      serveErrors: 1,
      serveAttempts: 6,
      servePercentage: 0.83,
      serveEfficiency: 0,
      serveRating: 1.9,
      setAssists: 10,
      setsTotal: 24,
      setErrors: 1,
      digs: 6,
      digErrors: 0,
      blockSingle: 1,
      blockMultiple: 0,
      blockErrors: 1,
      blocksPerSet: 0.5,
      setsPlayed: 2,
    },
    {
      name: "Laurel Barsocchini",
      kills: 1,
      attackErrors: 0,
      attackAttempts: 4,
      attackEfficiency: 0.25,
      killsPerSet: 0.5,
      serveAces: 2,
      serveErrors: 0,
      serveAttempts: 7,
      servePercentage: 1,
      serveEfficiency: 0.29,
      serveRating: 2.4,
      receivePerfect: 3,
      receivePositive: 3,
      receiveNegative: 1,
      receiveError: 1,
      receiveAttempts: 8,
      receivePercentage: 1.88,
      setAssists: 6,
      setsTotal: 20,
      setErrors: 0,
      digs: 9,
      digErrors: 1,
      setsPlayed: 2,
    },
    {
      name: "Victoria Davis",
      kills: 3,
      attackErrors: 1,
      attackAttempts: 9,
      attackEfficiency: 0.22,
      killsPerSet: 1.5,
      serveAces: 0,
      serveErrors: 1,
      serveAttempts: 6,
      servePercentage: 0.83,
      serveEfficiency: -0.17,
      serveRating: 1.3,
      digs: 3,
      digErrors: 0,
      blockSingle: 0,
      blockMultiple: 2,
      blockErrors: 1,
      blocksPerSet: 0.5,
      setsPlayed: 2,
    },
    {
      name: "Bridget Conley",
      kills: 5,
      attackErrors: 2,
      attackAttempts: 14,
      attackEfficiency: 0.21,
      killsPerSet: 2.5,
      receivePositive: 2,
      receiveNegative: 1,
      receiveAttempts: 3,
      receivePercentage: 1.67,
      setAssists: 1,
      setsTotal: 5,
      setErrors: 0,
      digs: 4,
      digErrors: 0,
      blockSingle: 1,
      blockMultiple: 0,
      blockErrors: 0,
      blocksPerSet: 0.5,
      setsPlayed: 2,
    },
    {
      name: "Hannah Shaffer",
      kills: 1,
      attackErrors: 1,
      attackAttempts: 7,
      attackEfficiency: 0,
      killsPerSet: 0.5,
      receiveError: 0,
      receiveAttempts: 2,
      digs: 3,
      digErrors: 1,
      blockSingle: 0,
      blockMultiple: 1,
      blockErrors: 0,
      blocksPerSet: 0.5,
      setsPlayed: 2,
    },
    {
      name: "Jaydin Watts",
      kills: 4,
      attackErrors: 1,
      attackAttempts: 12,
      attackEfficiency: 0.25,
      killsPerSet: 2,
      digs: 5,
      digErrors: 0,
      blockSingle: 1,
      blockMultiple: 1,
      blockErrors: 0,
      blocksPerSet: 1,
      setsPlayed: 2,
    },
    {
      name: "Benjamin Wilson",
      kills: 7,
      attackErrors: 3,
      attackAttempts: 16,
      attackEfficiency: 0.25,
      killsPerSet: 3.5,
      serveAces: 2,
      serveErrors: 1,
      serveAttempts: 10,
      servePercentage: 0.9,
      serveEfficiency: 0.1,
      serveRating: 2.0,
      setAssists: 4,
      setsTotal: 18,
      setErrors: 0,
      digs: 7,
      digErrors: 1,
      setsPlayed: 2,
    },
    {
      name: "Mia Lopez",
      kills: 2,
      attackErrors: 0,
      attackAttempts: 6,
      attackEfficiency: 0.33,
      killsPerSet: 1,
      serveAces: 1,
      serveErrors: 0,
      serveAttempts: 5,
      servePercentage: 1,
      serveEfficiency: 0.2,
      serveRating: 2.2,
      receivePerfect: 2,
      receivePositive: 2,
      receiveNegative: 0,
      receiveAttempts: 4,
      receivePercentage: 2.5,
      digs: 6,
      digErrors: 0,
      setsPlayed: 2,
    },
  ],
  [
    {
      name: "Milani Lee",
      kills: 7,
      attackErrors: 3,
      attackAttempts: 18,
      attackEfficiency: 0.22,
      killsPerSet: 3.5,
      serveAces: 1,
      serveErrors: 0,
      serveAttempts: 7,
      servePercentage: 1,
      serveEfficiency: 0.14,
      serveRating: 2.1,
      setAssists: 8,
      setsTotal: 24,
      setErrors: 1,
      digs: 6,
      digErrors: 0,
      setsPlayed: 2,
    },
    {
      name: "Jaydin Watts",
      kills: 5,
      attackErrors: 2,
      attackAttempts: 13,
      attackEfficiency: 0.23,
      killsPerSet: 2.5,
      blockSingle: 2,
      blockMultiple: 1,
      blockErrors: 0,
      blocksPerSet: 1.5,
      digs: 4,
      setsPlayed: 2,
    },
    {
      name: "Bridget Conley",
      kills: 3,
      attackErrors: 1,
      attackAttempts: 10,
      attackEfficiency: 0.2,
      killsPerSet: 1.5,
      receivePositive: 2,
      receiveNegative: 1,
      receiveAttempts: 3,
      receivePercentage: 1.67,
      setAssists: 1,
      digs: 5,
      setsPlayed: 2,
    },
    {
      name: "Laurel Barsocchini",
      serveAces: 1,
      serveErrors: 0,
      serveAttempts: 6,
      servePercentage: 1,
      serveEfficiency: 0.17,
      serveRating: 2.0,
      receivePerfect: 2,
      receivePositive: 2,
      receiveNegative: 0,
      receiveAttempts: 4,
      receivePercentage: 2.5,
      digs: 7,
      digErrors: 1,
      setsPlayed: 2,
    },
    {
      name: "Benjamin Wilson",
      kills: 8,
      attackErrors: 1,
      attackAttempts: 17,
      attackEfficiency: 0.41,
      killsPerSet: 4,
      blockSingle: 1,
      blockMultiple: 1,
      blockErrors: 0,
      blocksPerSet: 1,
      digs: 3,
      setsPlayed: 2,
    },
    {
      name: "Mia Lopez",
      serveAces: 1,
      serveErrors: 0,
      serveAttempts: 5,
      servePercentage: 1,
      serveEfficiency: 0.2,
      serveRating: 2.3,
      receivePerfect: 3,
      receivePositive: 1,
      receiveNegative: 0,
      receiveAttempts: 4,
      receivePercentage: 2.75,
      digs: 6,
      setsPlayed: 2,
    },
  ],
  [
    {
      name: "Madison Maxwell",
      kills: 12,
      attackErrors: 2,
      attackAttempts: 21,
      attackEfficiency: 0.48,
      killsPerSet: 6,
      serveAces: 1,
      serveErrors: 1,
      serveAttempts: 9,
      servePercentage: 0.89,
      serveEfficiency: 0,
      serveRating: 1.9,
      digs: 9,
      setsPlayed: 2,
    },
    {
      name: "Caroline Toberman",
      receivePerfect: 2,
      receivePositive: 2,
      receiveNegative: 1,
      receiveAttempts: 5,
      receivePercentage: 2,
      serveAces: 1,
      serveErrors: 0,
      serveAttempts: 6,
      servePercentage: 1,
      serveEfficiency: 0.17,
      serveRating: 2.2,
      digs: 4,
      setsPlayed: 2,
    },
    {
      name: "Victoria Davis",
      kills: 2,
      attackErrors: 2,
      attackAttempts: 8,
      attackEfficiency: 0,
      killsPerSet: 1,
      blockSingle: 1,
      blockMultiple: 2,
      blocksPerSet: 1.5,
      digs: 2,
      setsPlayed: 2,
    },
    {
      name: "Mia Lopez",
      serveAces: 1,
      serveErrors: 1,
      serveAttempts: 7,
      servePercentage: 0.86,
      serveEfficiency: 0,
      serveRating: 1.7,
      receivePerfect: 1,
      receivePositive: 2,
      receiveNegative: 1,
      receiveAttempts: 4,
      receivePercentage: 2,
      digs: 5,
      setsPlayed: 2,
    },
    {
      name: "Milani Lee",
      setAssists: 9,
      setsTotal: 26,
      setErrors: 0,
      kills: 4,
      attackErrors: 1,
      attackAttempts: 11,
      attackEfficiency: 0.27,
      killsPerSet: 2,
      digs: 6,
      setsPlayed: 2,
    },
    {
      name: "Bridget Conley",
      kills: 5,
      attackErrors: 2,
      attackAttempts: 13,
      attackEfficiency: 0.23,
      killsPerSet: 2.5,
      blockSingle: 0,
      blockMultiple: 1,
      blocksPerSet: 0.5,
      digs: 3,
      setsPlayed: 2,
    },
    {
      name: "Jaydin Watts",
      blockSingle: 2,
      blockMultiple: 2,
      blockErrors: 1,
      blocksPerSet: 2,
      digs: 4,
      setsPlayed: 2,
    },
  ],
  [
    {
      name: "Hannah Shaffer",
      receivePerfect: 2,
      receivePositive: 3,
      receiveNegative: 1,
      receiveError: 0,
      receiveAttempts: 6,
      receivePercentage: 2,
      digs: 7,
      digErrors: 0,
      setsPlayed: 2,
    },
    {
      name: "Caroline Toberman",
      serveAces: 2,
      serveErrors: 0,
      serveAttempts: 6,
      servePercentage: 1,
      serveEfficiency: 0.33,
      serveRating: 2.6,
      digs: 5,
      setsPlayed: 2,
    },
    {
      name: "Milani Lee",
      setAssists: 11,
      setsTotal: 28,
      setErrors: 0,
      kills: 3,
      attackErrors: 1,
      attackAttempts: 9,
      attackEfficiency: 0.22,
      digs: 6,
      setsPlayed: 2,
    },
    {
      name: "Mia Lopez",
      kills: 1,
      attackErrors: 0,
      attackAttempts: 3,
      attackEfficiency: 0.33,
      receivePerfect: 2,
      receivePositive: 2,
      receiveAttempts: 4,
      receivePercentage: 2.5,
      digs: 5,
      setsPlayed: 2,
    },
    {
      name: "Benjamin Wilson",
      kills: 6,
      attackErrors: 2,
      attackAttempts: 15,
      attackEfficiency: 0.27,
      killsPerSet: 3,
      blockSingle: 1,
      blockMultiple: 1,
      blocksPerSet: 1,
      setsPlayed: 2,
    },
    {
      name: "Jaydin Watts",
      kills: 2,
      attackErrors: 0,
      attackAttempts: 5,
      attackEfficiency: 0.4,
      killsPerSet: 1,
      blockSingle: 0,
      blockMultiple: 1,
      blockErrors: 0,
      blocksPerSet: 0.5,
      setsPlayed: 2,
    },
  ],
]
